name: Update External Docs
on:
    workflow_dispatch:

permissions:
    pull-requests: write
    contents: write

jobs:
    update-docs:
        runs-on: ubuntu-latest
        if: github.repository_owner == 'chrisdel101'
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Run scripts
              working-directory: .github/scripts
              run: |
                bash ./get-contributing.sh
                bash ./get-readmes.sh
                node ./get-express-version.mjs  